comment: false
codecov:
       token: 77ea3efd-3852-41aa-b49c-568055bab518
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
      enabled: false
